UPDATE "profiles" SET "sector" = CASE lower(btrim("sector"))
  WHEN 'ai-ml' THEN 'ai-ml'
  WHEN 'artificial intelligence' THEN 'ai-ml'
  WHEN 'machine learning' THEN 'ai-ml'
  WHEN 'neurotechnology' THEN 'ai-ml'
  WHEN 'developer-tools' THEN 'developer-tools'
  WHEN 'developer tools' THEN 'developer-tools'
  WHEN 'open source' THEN 'developer-tools'
  WHEN 'no-code software' THEN 'developer-tools'
  WHEN 'data-infrastructure' THEN 'data-infrastructure'
  WHEN 'data infrastructure' THEN 'data-infrastructure'
  WHEN 'fintech infrastructure' THEN 'data-infrastructure'
  WHEN 'saas-enterprise' THEN 'saas-enterprise'
  WHEN 'saas' THEN 'saas-enterprise'
  WHEN 'enterprise software' THEN 'saas-enterprise'
  WHEN 'productivity software' THEN 'saas-enterprise'
  WHEN 'workflow automation' THEN 'saas-enterprise'
  WHEN 'fintech' THEN 'fintech'
  WHEN 'banking as a service' THEN 'fintech'
  WHEN 'health-bio' THEN 'health-bio'
  WHEN 'health tech' THEN 'health-bio'
  WHEN 'security' THEN 'security'
  WHEN 'security & compliance' THEN 'security'
  WHEN 'hardware-robotics' THEN 'hardware-robotics'
  WHEN 'robotics' THEN 'hardware-robotics'
  WHEN 'autonomous vehicles' THEN 'hardware-robotics'
  WHEN 'aerospace' THEN 'hardware-robotics'
  WHEN 'augmented reality' THEN 'hardware-robotics'
  WHEN 'climate-energy' THEN 'climate-energy'
  WHEN 'climate technology' THEN 'climate-energy'
  WHEN 'consumer-marketplace' THEN 'consumer-marketplace'
  WHEN 'marketplace' THEN 'consumer-marketplace'
  WHEN 'community' THEN 'consumer-marketplace'
  WHEN 'vertical-saas' THEN 'vertical-saas'
  WHEN 'hr technology' THEN 'vertical-saas'
  WHEN 'legal technology' THEN 'vertical-saas'
  WHEN 'education' THEN 'vertical-saas'
  WHEN 'other' THEN 'other'
  WHEN 'nonprofit' THEN 'other'
  ELSE 'other'
END;
--> statement-breakpoint
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_sector_is_controlled" CHECK (sector in ('ai-ml', 'developer-tools', 'data-infrastructure', 'saas-enterprise', 'fintech', 'health-bio', 'security', 'hardware-robotics', 'climate-energy', 'consumer-marketplace', 'vertical-saas', 'other'));
