-- Ingest's own Postgres role, able to do what ingest does and nothing else. See docs/adr/0013.
--
-- The CREATE POLICY statements were generated by drizzle-kit from `db/schema.ts`. Everything
-- else is hand-written: Drizzle can name the role but cannot say what matters about it — its
-- attributes, its grants, and that it holds nothing more — so that is here, and the last
-- statement refuses to let the migration finish if the role that results is any broader.

-- Guarded because a role belongs to the whole cluster rather than to one database, so a scratch
-- cluster that has migrated some other database already has it. Whatever it was before, the
-- check at the end decides whether it is acceptable. No password: this file is committed, and
-- Jack sets one by hand, per the README.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rolodeck_ingest') THEN
    CREATE ROLE rolodeck_ingest WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
  END IF;
END
$$;--> statement-breakpoint
GRANT USAGE ON SCHEMA public TO rolodeck_ingest;--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE ON "profiles", "news_items", "events", "event_attendances" TO rolodeck_ingest;--> statement-breakpoint
-- `persistEvents` replaces an Event's Attendance on every run. The only delete ingest makes.
GRANT DELETE ON "event_attendances" TO rolodeck_ingest;--> statement-breakpoint
-- News ingest searches for Kept Company Profiles, and Kept lives in `swipes`, which ingest holds
-- no grant on. This function answers that one question — which profile ids an owner Kept — and
-- nothing else about `swipes`. SECURITY DEFINER so it reads as its owner, the migrating role,
-- which owns `swipes`; an empty search_path so nothing ingest could create changes what the
-- body resolves to. In its own schema rather than `public`, because PostgREST exposes `public`
-- as RPC and Supabase grants EXECUTE on `public` functions to `anon` by default.
CREATE SCHEMA ingest;--> statement-breakpoint
REVOKE ALL ON SCHEMA ingest FROM PUBLIC;--> statement-breakpoint
GRANT USAGE ON SCHEMA ingest TO rolodeck_ingest;--> statement-breakpoint
CREATE FUNCTION ingest.kept_profile_ids(for_owner uuid) RETURNS SETOF uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT profile_id FROM public.swipes WHERE user_id = for_owner AND decision = 'keep'
$$;--> statement-breakpoint
REVOKE ALL ON FUNCTION ingest.kept_profile_ids(uuid) FROM PUBLIC, anon, authenticated;--> statement-breakpoint
GRANT EXECUTE ON FUNCTION ingest.kept_profile_ids(uuid) TO rolodeck_ingest;--> statement-breakpoint
CREATE POLICY "event_attendances_ingest_select" ON "event_attendances" AS PERMISSIVE FOR SELECT TO "rolodeck_ingest" USING (true);--> statement-breakpoint
CREATE POLICY "event_attendances_ingest_insert" ON "event_attendances" AS PERMISSIVE FOR INSERT TO "rolodeck_ingest" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "event_attendances_ingest_update" ON "event_attendances" AS PERMISSIVE FOR UPDATE TO "rolodeck_ingest" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "event_attendances_ingest_delete" ON "event_attendances" AS PERMISSIVE FOR DELETE TO "rolodeck_ingest" USING (true);--> statement-breakpoint
CREATE POLICY "events_ingest_select" ON "events" AS PERMISSIVE FOR SELECT TO "rolodeck_ingest" USING (true);--> statement-breakpoint
CREATE POLICY "events_ingest_insert" ON "events" AS PERMISSIVE FOR INSERT TO "rolodeck_ingest" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "events_ingest_update" ON "events" AS PERMISSIVE FOR UPDATE TO "rolodeck_ingest" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "news_items_ingest_select" ON "news_items" AS PERMISSIVE FOR SELECT TO "rolodeck_ingest" USING (true);--> statement-breakpoint
CREATE POLICY "news_items_ingest_insert" ON "news_items" AS PERMISSIVE FOR INSERT TO "rolodeck_ingest" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "news_items_ingest_update" ON "news_items" AS PERMISSIVE FOR UPDATE TO "rolodeck_ingest" USING (true) WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "profiles_ingest_select" ON "profiles" AS PERMISSIVE FOR SELECT TO "rolodeck_ingest" USING (true);--> statement-breakpoint
CREATE POLICY "profiles_ingest_insert" ON "profiles" AS PERMISSIVE FOR INSERT TO "rolodeck_ingest" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "profiles_ingest_update" ON "profiles" AS PERMISSIVE FOR UPDATE TO "rolodeck_ingest" USING (true) WITH CHECK (true);--> statement-breakpoint
-- The role must be exactly what this file says, on whatever database it runs against — including
-- the real Supabase project, where the tests never run. `has_table_privilege` counts grants made
-- to PUBLIC and inherited through membership, so this also catches a right the role holds that
-- nothing above granted it.
DO $$
DECLARE
  ingest_role oid := (SELECT oid FROM pg_roles WHERE rolname = 'rolodeck_ingest');
  broader text;
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_roles
    WHERE oid = ingest_role
      AND (rolsuper OR rolcreaterole OR rolcreatedb OR rolreplication OR rolbypassrls)
  ) THEN
    RAISE EXCEPTION 'rolodeck_ingest may not be a superuser, create roles or databases, replicate, or bypass RLS';
  END IF;

  -- A member inherits, or can SET ROLE into, whatever the role it belongs to may do.
  IF EXISTS (SELECT 1 FROM pg_auth_members WHERE member = ingest_role) THEN
    RAISE EXCEPTION 'rolodeck_ingest may not be a member of any other role';
  END IF;

  SELECT string_agg(format('%I.%I', n.nspname, c.relname), ', ' ORDER BY n.nspname, c.relname)
  INTO broader
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE c.relkind IN ('r', 'p', 'v', 'm', 'f')
    AND n.nspname IN ('public', 'auth')
    AND NOT (n.nspname = 'public' AND c.relname IN ('profiles', 'news_items', 'events', 'event_attendances'))
    AND (
      has_table_privilege(ingest_role, c.oid, 'SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER')
      OR has_any_column_privilege(ingest_role, c.oid, 'SELECT, INSERT, UPDATE, REFERENCES')
    );

  IF broader IS NOT NULL THEN
    RAISE EXCEPTION 'rolodeck_ingest may hold no privilege beyond its four tables, but can reach %', broader;
  END IF;

  -- TRUNCATE is checked on its own tables too: unlike DELETE, it does not consult RLS at all.
  SELECT string_agg(c.relname, ', ' ORDER BY c.relname)
  INTO broader
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname IN ('profiles', 'news_items', 'events', 'event_attendances')
    AND (
      has_table_privilege(ingest_role, c.oid, 'TRUNCATE, REFERENCES, TRIGGER')
      OR (c.relname <> 'event_attendances' AND has_table_privilege(ingest_role, c.oid, 'DELETE'))
    );

  IF broader IS NOT NULL THEN
    RAISE EXCEPTION 'rolodeck_ingest may only select, insert and update (and delete Attendance), but holds more on %', broader;
  END IF;
END
$$;
