-- Company Profiles, News, Events and Attendances become a shared Catalogue that nothing owns.
-- See docs/adr/0019, which also records why a system account and a per-User copy were rejected.
--
-- Everything below the first statement was generated by drizzle-kit from `db/schema.ts`, except
-- that the four `ALTER POLICY` statements it wrote are spelled here as a DROP and a CREATE: a
-- policy that now says `true` must not keep a name ending `_own`, and a rename is a drop and a
-- create to Postgres anyway.
--
-- The first statement is hand-written and is the dangerous one. Reverting a commit does not
-- unmake a schema change (docs/adr/0014), and this one deletes rows.

-- The old keys were `(owner_id, source, name_key)` and `(owner_id, source, external_id)`; the new
-- ones drop the owner, so two rows that differed only by who held them now collide. This collapses
-- each such group onto its oldest row before the unique indexes below are built, and reports how
-- many it removed. With one account there are none, and a run that collapses nothing is a pass,
-- not a failure — the count is printed either way so a silent zero is still a stated zero.
--
-- A Keep, an article or an Attendance pointing at a row that loses is repointed at the one that
-- wins rather than cascading away with it: those are facts about the company, not about which
-- duplicate of it a row happened to name. Where repointing would collide with a row the winner
-- already has — the same User having Kept both, the same article stored against both — the loser's
-- is deleted first, because the pair is the natural key and one of them has to go.
DO $$
DECLARE
  collapsed_profiles bigint := 0;
  collapsed_events bigint := 0;
BEGIN
  CREATE TEMP TABLE collapsed_profile_ids AS
  SELECT p.id, winner.keeper
    FROM public.profiles p
    JOIN (
      SELECT source, name_key, (array_agg(id ORDER BY created_at, id))[1] AS keeper
        FROM public.profiles
       GROUP BY source, name_key
      HAVING count(*) > 1
    ) winner ON winner.source = p.source AND winner.name_key = p.name_key
   WHERE p.id <> winner.keeper;

  DELETE FROM public.swipes s
   USING collapsed_profile_ids d
   WHERE s.profile_id = d.id
     AND EXISTS (
       SELECT 1 FROM public.swipes kept
        WHERE kept.profile_id = d.keeper AND kept.user_id = s.user_id
     );
  UPDATE public.swipes s
     SET profile_id = d.keeper
    FROM collapsed_profile_ids d
   WHERE s.profile_id = d.id;

  DELETE FROM public.news_items n
   USING collapsed_profile_ids d
   WHERE n.profile_id = d.id
     AND EXISTS (
       SELECT 1 FROM public.news_items kept
        WHERE kept.profile_id = d.keeper AND kept.url = n.url
     );
  UPDATE public.news_items n
     SET profile_id = d.keeper
    FROM collapsed_profile_ids d
   WHERE n.profile_id = d.id;

  DELETE FROM public.event_attendances a
   USING collapsed_profile_ids d
   WHERE a.profile_id = d.id
     AND EXISTS (
       SELECT 1 FROM public.event_attendances kept
        WHERE kept.profile_id = d.keeper AND kept.event_id = a.event_id
     );
  UPDATE public.event_attendances a
     SET profile_id = d.keeper
    FROM collapsed_profile_ids d
   WHERE a.profile_id = d.id;

  DELETE FROM public.profiles p USING collapsed_profile_ids d WHERE p.id = d.id;
  GET DIAGNOSTICS collapsed_profiles = ROW_COUNT;
  DROP TABLE collapsed_profile_ids;

  CREATE TEMP TABLE collapsed_event_ids AS
  SELECT e.id, winner.keeper
    FROM public.events e
    JOIN (
      SELECT source, external_id, (array_agg(id ORDER BY created_at, id))[1] AS keeper
        FROM public.events
       GROUP BY source, external_id
      HAVING count(*) > 1
    ) winner ON winner.source = e.source AND winner.external_id = e.external_id
   WHERE e.id <> winner.keeper;

  DELETE FROM public.event_attendances a
   USING collapsed_event_ids d
   WHERE a.event_id = d.id
     AND EXISTS (
       SELECT 1 FROM public.event_attendances kept
        WHERE kept.event_id = d.keeper AND kept.profile_id = a.profile_id
     );
  UPDATE public.event_attendances a
     SET event_id = d.keeper
    FROM collapsed_event_ids d
   WHERE a.event_id = d.id;

  DELETE FROM public.events e USING collapsed_event_ids d WHERE e.id = d.id;
  GET DIAGNOSTICS collapsed_events = ROW_COUNT;
  DROP TABLE collapsed_event_ids;

  RAISE NOTICE 'Collapsed % cross-owner duplicate Company Profiles and % duplicate Events.',
    collapsed_profiles, collapsed_events;
END
$$;--> statement-breakpoint
ALTER TABLE "events" DROP CONSTRAINT "events_owner_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "news_items" DROP CONSTRAINT "news_items_owner_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "profiles" DROP CONSTRAINT "profiles_owner_id_users_id_fk";
--> statement-breakpoint
DROP INDEX "events_owner_id_source_external_id_idx";--> statement-breakpoint
DROP INDEX "events_owner_id_start_date_idx";--> statement-breakpoint
DROP INDEX "news_items_owner_id_published_at_idx";--> statement-breakpoint
DROP INDEX "profiles_owner_id_source_name_key_idx";--> statement-breakpoint
DROP INDEX "profiles_owner_id_created_at_id_idx";--> statement-breakpoint
CREATE UNIQUE INDEX "events_source_external_id_idx" ON "events" USING btree ("source","external_id");--> statement-breakpoint
CREATE INDEX "events_start_date_idx" ON "events" USING btree ("start_date");--> statement-breakpoint
CREATE INDEX "news_items_published_at_idx" ON "news_items" USING btree ("published_at" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "profiles_source_name_key_idx" ON "profiles" USING btree ("source","name_key");--> statement-breakpoint
CREATE INDEX "profiles_created_at_id_idx" ON "profiles" USING btree ("created_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
-- Before the columns, not after: a policy whose `using` clause names `owner_id` depends on the
-- column, and Postgres refuses to drop a column something still depends on.
DROP POLICY "event_attendances_select_own" ON "event_attendances";--> statement-breakpoint
DROP POLICY "events_select_own" ON "events";--> statement-breakpoint
DROP POLICY "news_items_select_own" ON "news_items";--> statement-breakpoint
DROP POLICY "profiles_select_own" ON "profiles";--> statement-breakpoint
-- Dropping the column drops `rolodeck_ingest`'s UPDATE grant on it with it, so ingest cannot
-- write an owner after this for the plainest possible reason: there is nowhere to write one.
ALTER TABLE "events" DROP COLUMN "owner_id";--> statement-breakpoint
ALTER TABLE "news_items" DROP COLUMN "owner_id";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN "owner_id";--> statement-breakpoint
-- Reads widen to `authenticated` and never to `anon`, which holds no policy on any of these
-- tables and so still reads nothing. `db/profiles.test.ts` and its neighbours assert that per
-- table, through the same handle the rest of the suite uses.
CREATE POLICY "event_attendances_select_catalogue" ON "event_attendances" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "events_select_catalogue" ON "events" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "news_items_select_catalogue" ON "news_items" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "profiles_select_catalogue" ON "profiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
