-- Company Profiles, News, Events and Attendances become a shared Catalogue that nothing owns.
-- See docs/adr/0019, which also records why a system account and a per-User copy were rejected.
--
-- Everything below the first statement was generated by drizzle-kit from `db/schema.ts`, except
-- that the four `ALTER POLICY` statements it wrote are spelled here as a DROP and a CREATE: a
-- policy that now says `true` must not keep a name ending `_own`, and a rename is a drop and a
-- create to Postgres anyway.
--
-- The first statement is hand-written and is the dangerous one. Reverting a commit does not
-- unmake a schema change (docs/adr/0014), and this one deletes rows.

-- The old keys were `(owner_id, source, name_key)` and `(owner_id, source, external_id)`; the new
-- ones drop the owner, so two rows that differed only by who held them now collide. This collapses
-- each such group onto its oldest row before the unique indexes below are built, and reports how
-- many it removed. With one account there are none, and a run that collapses nothing is a pass,
-- not a failure — the count is printed either way so a silent zero is still a stated zero.
--
-- A Keep, an article or an Attendance pointing at a row that loses is repointed at the one that
-- wins rather than cascading away with it: those are facts about the company, not about which
-- duplicate of it a row happened to name. Where repointing would collide — the same User having
-- Kept two of them, the same article stored against two of them — all but one of the colliding
-- rows is deleted first, because the pair is the natural key and only one of them can survive.
--
-- "All but one", chosen by ranking the whole group at once, rather than "the loser's, where the
-- keeper already has it". Nothing bounds a group at two: `ROLODECK_OWNER_ID` was one account by
-- convention only, and three rows sharing a key repoint two losers onto one keeper. A pairwise
-- test against the keeper passes for both of them when the keeper holds no such row itself, and
-- then the one `UPDATE` sets two rows to the same key and aborts the migration on a constraint
-- the schema has had all along. So the keeper is mapped to itself below and ranked alongside its
-- losers: `rn = 1` is the row that survives, and it is the keeper's own wherever one exists.
DO $$
DECLARE
  collapsed_profiles bigint := 0;
  collapsed_events bigint := 0;
BEGIN
  -- Every row of a colliding group, keeper included, mapped to the row that wins.
  CREATE TEMP TABLE collapsed_profile_ids AS
  SELECT p.id, winner.keeper
    FROM public.profiles p
    JOIN (
      SELECT source, name_key, (array_agg(id ORDER BY created_at, id))[1] AS keeper
        FROM public.profiles
       GROUP BY source, name_key
      HAVING count(*) > 1
    ) winner ON winner.source = p.source AND winner.name_key = p.name_key;

  -- A Keep is identified by `(user_id, profile_id)` and will be keyed `(user_id, keeper)`. The
  -- decision that survives is the keeper's, else the earliest a loser recorded.
  DELETE FROM public.swipes s
   USING (
     SELECT s.user_id,
            s.profile_id,
            row_number() OVER (
              PARTITION BY s.user_id, d.keeper
              ORDER BY (s.profile_id = d.keeper) DESC, s.decided_at, s.profile_id
            ) AS rn
       FROM public.swipes s
       JOIN collapsed_profile_ids d ON d.id = s.profile_id
   ) dup
   WHERE dup.rn > 1
     AND s.user_id = dup.user_id
     AND s.profile_id = dup.profile_id;
  UPDATE public.swipes s
     SET profile_id = d.keeper
    FROM collapsed_profile_ids d
   WHERE s.profile_id = d.id
     AND d.id <> d.keeper;

  -- An article is identified by its own `id` and will be keyed `(keeper, url)`.
  DELETE FROM public.news_items n
   USING (
     SELECT n.id,
            row_number() OVER (
              PARTITION BY d.keeper, n.url
              ORDER BY (n.profile_id = d.keeper) DESC, n.fetched_at, n.id
            ) AS rn
       FROM public.news_items n
       JOIN collapsed_profile_ids d ON d.id = n.profile_id
   ) dup
   WHERE dup.rn > 1
     AND n.id = dup.id;
  UPDATE public.news_items n
     SET profile_id = d.keeper
    FROM collapsed_profile_ids d
   WHERE n.profile_id = d.id
     AND d.id <> d.keeper;

  -- An Attendance is the pair itself, so two that collapse onto one are the same fact twice and
  -- which copy survives cannot be told apart.
  DELETE FROM public.event_attendances a
   USING (
     SELECT a.event_id,
            a.profile_id,
            row_number() OVER (
              PARTITION BY a.event_id, d.keeper
              ORDER BY (a.profile_id = d.keeper) DESC, a.profile_id
            ) AS rn
       FROM public.event_attendances a
       JOIN collapsed_profile_ids d ON d.id = a.profile_id
   ) dup
   WHERE dup.rn > 1
     AND a.event_id = dup.event_id
     AND a.profile_id = dup.profile_id;
  UPDATE public.event_attendances a
     SET profile_id = d.keeper
    FROM collapsed_profile_ids d
   WHERE a.profile_id = d.id
     AND d.id <> d.keeper;

  DELETE FROM public.profiles p
   USING collapsed_profile_ids d
   WHERE p.id = d.id
     AND d.id <> d.keeper;
  GET DIAGNOSTICS collapsed_profiles = ROW_COUNT;
  DROP TABLE collapsed_profile_ids;

  CREATE TEMP TABLE collapsed_event_ids AS
  SELECT e.id, winner.keeper
    FROM public.events e
    JOIN (
      SELECT source, external_id, (array_agg(id ORDER BY created_at, id))[1] AS keeper
        FROM public.events
       GROUP BY source, external_id
      HAVING count(*) > 1
    ) winner ON winner.source = e.source AND winner.external_id = e.external_id;

  DELETE FROM public.event_attendances a
   USING (
     SELECT a.event_id,
            a.profile_id,
            row_number() OVER (
              PARTITION BY d.keeper, a.profile_id
              ORDER BY (a.event_id = d.keeper) DESC, a.event_id
            ) AS rn
       FROM public.event_attendances a
       JOIN collapsed_event_ids d ON d.id = a.event_id
   ) dup
   WHERE dup.rn > 1
     AND a.event_id = dup.event_id
     AND a.profile_id = dup.profile_id;
  UPDATE public.event_attendances a
     SET event_id = d.keeper
    FROM collapsed_event_ids d
   WHERE a.event_id = d.id
     AND d.id <> d.keeper;

  DELETE FROM public.events e
   USING collapsed_event_ids d
   WHERE e.id = d.id
     AND d.id <> d.keeper;
  GET DIAGNOSTICS collapsed_events = ROW_COUNT;
  DROP TABLE collapsed_event_ids;

  RAISE NOTICE 'Collapsed % cross-owner duplicate Company Profiles and % duplicate Events.',
    collapsed_profiles, collapsed_events;
END
$$;--> statement-breakpoint
ALTER TABLE "events" DROP CONSTRAINT "events_owner_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "news_items" DROP CONSTRAINT "news_items_owner_id_users_id_fk";
--> statement-breakpoint
ALTER TABLE "profiles" DROP CONSTRAINT "profiles_owner_id_users_id_fk";
--> statement-breakpoint
DROP INDEX "events_owner_id_source_external_id_idx";--> statement-breakpoint
DROP INDEX "events_owner_id_start_date_idx";--> statement-breakpoint
DROP INDEX "news_items_owner_id_published_at_idx";--> statement-breakpoint
DROP INDEX "profiles_owner_id_source_name_key_idx";--> statement-breakpoint
DROP INDEX "profiles_owner_id_created_at_id_idx";--> statement-breakpoint
CREATE UNIQUE INDEX "events_source_external_id_idx" ON "events" USING btree ("source","external_id");--> statement-breakpoint
CREATE INDEX "events_start_date_idx" ON "events" USING btree ("start_date");--> statement-breakpoint
CREATE INDEX "news_items_published_at_idx" ON "news_items" USING btree ("published_at" DESC NULLS LAST);--> statement-breakpoint
CREATE UNIQUE INDEX "profiles_source_name_key_idx" ON "profiles" USING btree ("source","name_key");--> statement-breakpoint
CREATE INDEX "profiles_created_at_id_idx" ON "profiles" USING btree ("created_at" DESC NULLS LAST,"id" DESC NULLS LAST);--> statement-breakpoint
-- Before the columns, not after: a policy whose `using` clause names `owner_id` depends on the
-- column, and Postgres refuses to drop a column something still depends on.
DROP POLICY "event_attendances_select_own" ON "event_attendances";--> statement-breakpoint
DROP POLICY "events_select_own" ON "events";--> statement-breakpoint
DROP POLICY "news_items_select_own" ON "news_items";--> statement-breakpoint
DROP POLICY "profiles_select_own" ON "profiles";--> statement-breakpoint
-- Dropping the column drops `rolodeck_ingest`'s UPDATE grant on it with it, so ingest cannot
-- write an owner after this for the plainest possible reason: there is nowhere to write one.
ALTER TABLE "events" DROP COLUMN "owner_id";--> statement-breakpoint
ALTER TABLE "news_items" DROP COLUMN "owner_id";--> statement-breakpoint
ALTER TABLE "profiles" DROP COLUMN "owner_id";--> statement-breakpoint
-- Reads widen to `authenticated` and never to `anon`, which holds no policy on any of these
-- tables and so still reads nothing. `db/profiles.test.ts` and its neighbours assert that per
-- table, through the same handle the rest of the suite uses.
CREATE POLICY "event_attendances_select_catalogue" ON "event_attendances" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "events_select_catalogue" ON "events" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "news_items_select_catalogue" ON "news_items" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);--> statement-breakpoint
CREATE POLICY "profiles_select_catalogue" ON "profiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
