import { sql } from "drizzle-orm";
import {
  check,
  index,
  jsonb,
  pgPolicy,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { authUid, authUsers, authenticatedRole } from "drizzle-orm/supabase";

import { SECTOR_VALUES } from "./profile-input";
import {
  PROVENANCE_VALUES,
  PROVENANCED_FIELDS,
  type ProfileProvenance,
} from "./provenance";

const provenanceLiterals = PROVENANCE_VALUES.map((value) => `'${value}'`).join(
  ", ",
);

const sectorLiterals = SECTOR_VALUES.map((value) => `'${value}'`).join(", ");

const hasValidProvenance = (field: string) =>
  `provenance ->> '${field}' in (${provenanceLiterals})`;

/**
 * The database's own half of the per-field provenance rule. Zod guards the boundary in
 * TypeScript; this guards it for anything that reaches Postgres another way, including the
 * service-role ingest path, which bypasses RLS but not a check constraint.
 */
const provenanceCoversEveryField = sql.raw(
  // A CHECK passes when it evaluates to NULL, and `null in (...)` is NULL, so a field with
  // no provenance key at all would slip through unwrapped. The coalesce is what turns a
  // missing field into a rejection rather than a silently unattributed value.
  `coalesce(\n  ${[
    ...PROVENANCED_FIELDS.filter((field) => field !== "website").map(
      hasValidProvenance,
    ),
    // `website` is the one nullable Profile field: it carries provenance exactly when it
    // has a value to attribute.
    `(website is null) = (provenance ->> 'website' is null)`,
    `(website is null or ${hasValidProvenance("website")})`,
  ].join("\n  and ")}\n, false)`,
);

export const profiles = pgTable(
  "profiles",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /**
     * V1 is single-player, but every Profile is owned from day one so RLS has something to
     * match on and multi-user stays additive rather than a migration. See CLAUDE.md.
     */
    ownerId: uuid("owner_id")
      .notNull()
      .references(() => authUsers.id, { onDelete: "cascade" }),
    /**
     * Which ingest path wrote this row: `yc`, `sec-form-d`, and so on. Not a Profile field and
     * so not provenanced — `provenance` says what kind of value each field is, per CONTEXT.md,
     * while this says which pipeline produced the record. It is half the natural key below.
     */
    source: text("source").notNull(),
    name: text("name").notNull(),
    description: text("description").notNull(),
    sector: text("sector").notNull(),
    stage: text("stage").notNull(),
    website: text("website"),
    provenance: jsonb("provenance").$type<ProfileProvenance>().notNull(),
    /**
     * The name reduced to what identity actually depends on: case-folded, with runs of
     * whitespace collapsed and the ends trimmed. Generated by Postgres rather than computed in
     * TypeScript so that the key a row is deduplicated on cannot disagree with the name it
     * carries, whichever path wrote it. See docs/adr/0008.
     */
    nameKey: text("name_key").generatedAlwaysAs(
      // POSIX `[[:space:]]` rather than `\s`, which a TypeScript template literal would eat
      // before Postgres ever saw it. Every function here is IMMUTABLE, as a generated column
      // requires.
      sql`lower(btrim(regexp_replace(name, '[[:space:]]+', ' ', 'g')))`,
    ),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    check("profiles_provenance_covers_every_field", provenanceCoversEveryField),
    /**
     * The database's own half of the Sector vocabulary being closed. Zod guards the boundary
     * in TypeScript; this guards it for the service-role ingest path, which bypasses RLS but
     * not a check constraint, so `sector` cannot drift back to free text through it.
     */
    check("profiles_sector_is_controlled", sql.raw(`sector in (${sectorLiterals})`)),
    /**
     * The natural key ingest is idempotent on: one Profile per company name, per source, per
     * owner. It is a constraint rather than a convention because the write path runs under the
     * secret key — the one credential that bypasses RLS — and a duplicate it created would be
     * a second card for the same company in the Deck, not an error anything would raise. See
     * docs/adr/0008.
     */
    uniqueIndex("profiles_owner_id_source_name_key_idx").on(
      table.ownerId,
      table.source,
      table.nameKey,
    ),
    /**
     * The Deck is paginated by keyset on exactly this order, so the index carries the whole
     * `where` and `order by` of `readDeckPage` — see `db/deck.ts`.
     */
    index("profiles_owner_id_created_at_id_idx").on(
      table.ownerId,
      table.createdAt.desc(),
      table.id.desc(),
    ),
    /**
     * The only way to read a Profile is to be signed in as its owner. Defining any policy
     * makes Drizzle enable RLS on the table, so the anonymous role — which Supabase grants
     * table privileges to by default — matches no policy and sees no rows.
     */
    pgPolicy("profiles_select_own", {
      for: "select",
      to: authenticatedRole,
      using: sql`${authUid} = ${table.ownerId}`,
    }),
  ],
);

export type Profile = typeof profiles.$inferSelect;
export type NewProfile = typeof profiles.$inferInsert;

/**
 * The two swipe actions, spelled as CONTEXT.md spells them. Keep marks a Profile worth a
 * conversation; Pass dismisses it from the current Deck without deleting the Profile, which
 * is why a decision is a row of its own rather than a column on `profiles`.
 */
export const SWIPE_DECISIONS = ["keep", "pass"] as const;

export type SwipeDecision = (typeof SWIPE_DECISIONS)[number];

const decisionLiterals = SWIPE_DECISIONS.map((value) => `'${value}'`).join(
  ", ",
);

export const swipes = pgTable(
  "swipes",
  {
    profileId: uuid("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    userId: uuid("user_id")
      .notNull()
      .references(() => authUsers.id, { onDelete: "cascade" }),
    decision: text("decision").$type<SwipeDecision>().notNull(),
    decidedAt: timestamp("decided_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    /**
     * One decision per user per Profile: swiping again is a correction, not a second row, so
     * the Deck cannot end up excluding a Profile for two contradictory reasons.
     */
    primaryKey({ columns: [table.userId, table.profileId] }),
    // Text plus a check rather than an enum, matching how `provenance` is constrained: the
    // set is closed in Postgres as well as in TypeScript, including for the ingest path.
    check(
      "swipes_decision_is_a_swipe",
      sql.raw(`decision in (${decisionLiterals})`),
    ),
    pgPolicy("swipes_select_own", {
      for: "select",
      to: authenticatedRole,
      using: sql`${authUid} = ${table.userId}`,
    }),
    /**
     * A decision can only ever be recorded, or corrected, against the signed-in user, and
     * only about a Profile that user can see. A foreign key does not consult RLS, so without
     * the `exists` — which reads `profiles` through its own policy — an id belonging to
     * somebody else would be accepted here. There is deliberately no delete policy: nothing
     * in the app un-swipes a Profile.
     */
    pgPolicy("swipes_insert_own", {
      for: "insert",
      to: authenticatedRole,
      withCheck: sql`${authUid} = ${table.userId} and exists (select 1 from ${profiles} where ${profiles.id} = ${table.profileId})`,
    }),
    pgPolicy("swipes_update_own", {
      for: "update",
      to: authenticatedRole,
      using: sql`${authUid} = ${table.userId}`,
      withCheck: sql`${authUid} = ${table.userId} and exists (select 1 from ${profiles} where ${profiles.id} = ${table.profileId})`,
    }),
  ],
);

export type Swipe = typeof swipes.$inferSelect;
export type NewSwipe = typeof swipes.$inferInsert;
